kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-io-fault-user-db-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: user-db
  mode: all
  action: fault
  errno: 5
  percent: 10
  volumePath: /data/db
  duration: 180s
