kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-network-partition-catalogue-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: catalogue
    pods:
      sock-shop:
        - catalogue-58bdd4d4f9-48jpd
  mode: one
  action: partition
  duration: 180s
  direction: to
