kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-cpu-hog-user-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: user
    pods:
      sock-shop:
        - user-5c64496568-7jpx8
  mode: one
  stressors:
    cpu:
      workers: 1
      load: 70
  duration: 180s
