kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-network-partition-front-end-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: front-end
    pods:
      sock-shop:
        - front-end-65f844fc76-9z5xb
  mode: one
  action: partition
  duration: 180s
  direction: to
