kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-network-loss-shipping-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: shipping
    pods:
      sock-shop:
        - shipping-66d8f78d5f-9rcrc
  mode: one
  action: loss
  duration: 180s
  loss:
    loss: '30'
    correlation: '25'
  direction: to
