kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-do-fault-catalogue-db-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: catalogue-db
  mode: all
  action: pod-failure
  duration: 60s
