kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-memory-hog-carts-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: carts
    pods:
      sock-shop:
        - carts-5b77c45b65-ks75w
  mode: one
  stressors:
    memory:
      workers: 1
      size: 600M
  duration: 180s
