kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-do-fault-payment-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: payment
    pods:
      sock-shop:
        - payment-664c4d4c74-r8lxz
  mode: one
  action: pod-failure
  duration: 60s
