kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: pod-cpu-hog-payment-001
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: payment
    pods:
      sock-shop:
        - payment-664c4d4c74-r8lxz
  mode: one
  stressors:
    cpu:
      workers: 1
      load: 70
  duration: 180s
